#%RAML 1.0

title: Book Library API
version: v0.1

documentation:
  - title: Introduction
    content: Automated access to books
  - title: Licensing
    content: Please respect copyrights on our books.

types:
  nataliaBook: !include nataliaBook.json
  nataliaBookCollection: !include bookCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/nataliaBook:
  displayName: Books
  description: The collection of library books
  get:
    description: Get a collection of the books.
    responses:
      200:
        description: OK
        body:
          application/json:
            description: Get a collection of the books
            type: nataliaBookCollection
            example:
              strict: false
              value: !include examples/bookCollection.sample
  post:
    description: Create a new Custom Book.
    headers:
      Content-Type:
        example: application/json
    body:
      application/json:
        description: Create a new Custom Book.
        type: nataliaBook
        example:
          strict: false
          value: !include examples/post_book.sample
    responses:
      200:
        description: OK
        body:
          application/json:
            description: The server has successfully fulfilled the POST request.
            type: nataliaBook
            example:
              strict: false
              value: !include examples/book1.sample
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  /{id}:
    displayName: Book
    description: Get a specific book
    type:
      collection-item:
        schema: nataliaBook
        exampleItem: !include examples/book.sample
    get:
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
