##%RAML 1.0 Extension
#
#extends: pets.raml
#title: Pets
#version: v0.1
#protocols: [ HTTP, HTTPS ]
#baseUri: http://localhost
#usage: |
#  To provide user documentation and other descriptive text in Spanish
#  (Para proporcionar la documentación del usuario y otro texto descriptivo
#  en español)
#
#types:
#  pet: !include pet.json
#  errors: !include raml-util/schemas/errors.schema
#
#/pets:
#  /{id}:
#    displayName: Get pet by id
#    description: Retrieve a specific pet by given id.
#    get:
#      description: Retrieve a specific pet by given id.
#      responses:
#        200:
#          description: OK
#          body:
#            application/json:
#              description: Pet details.
#              type: pet
