##%RAML 1.0
#
#title: Pets
#version: v0.1
#protocols: [ HTTP, HTTPS ]
#baseUri: http://localhost
#
#documentation:
#  - title: Pets API
#    content: This documents the API calls that can be made to manage pets
#
#types:
#  petsCollection: !include petsCollection.json
#  errors: !include raml-util/schemas/errors.schema
#
#traits:
#  validate: !include raml-util/traits/validation.raml
#  language: !include raml-util/traits/language.raml
#  pageable:  !include raml-util/traits/pageable.raml
#  searchable: !include raml-util/traits/searchable.raml
#
#
#/pets:
#  displayName: Pets
#  description: Pets that live here
#  get:
#    description: Details of pets.
#    responses:
#      200:
#        description: OK
#        body:
#          application/json:
#            description: Details of pets.
#            type: petsCollection
#      500:
#        description: "Internal server error"
#        body:
#          text/plain:
#            example: "Internal server error, contact administrator"
